data:
  cache_dir: "gs://levanter-data-new/tokenized/pile-old/"
  tokenizer: "EleutherAI/gpt-neox-20b"
model:
  hidden_dim: 1536
  num_heads: 24
  num_layers: 48
  seq_len: 1024
  gradient_checkpointing: true
  scale_attn_by_inverse_layer_idx: true
trainer:
  wandb:
    project: "levanter"
    tags: ["pile", "gpt2"]

  mp: p=f32,c=bfloat16
  learning_rate: 1.2E-4
  weight_decay: 0.1
  model_axis_size: 1
  per_device_parallelism: -1
  per_device_eval_parallelism: 8

  train_batch_size: 512
  num_train_steps: 200000
  steps_per_eval: 1000
  min_lr_ratio: 0.1
